### ISSUE TITLE
isOnline check fails if behind an HTTP Proxy

### ISSUE THREAD

**Issue by eevans-seattle** [Microsoft/vscode-azure-account#121]
https://github.com/Microsoft/vscode-azure-account/blob/0f7860c6d91286e7a55267a4fb20ae845c00b616/src/azure-account.ts#L883

In my environment, a Sign In attempt fails with the error "You appear to be offline. Please check your network connection."  This issue appears to be related to the "isOnline" check.

I am executing in a corporate network which uses an HTTP proxy for all outgoing HTTP requests.  My network does not allow direct DNS resolution of external domain names.  All DNS lookups for external domains are performed by the proxy.  The isOnline check appears to be dependent upon being able to successfully resolve a DNS lookup.  Since my machine cannot perform the lookup, the isOnline check fails and I am unable to Sign In.

The isOnline check should either be eliminated to allow the TCP connection to fail "naturally" if not online, or updated to utilize some other means to determine Internet connectivity that does not rely upon DNS lookups.

**Comment by rwaal** [comment]
I have been lead to this Github issue via [https://github.com/Microsoft/vscode-azure-account/issues/27](url) while troubleshooting sign in problems with the Azure Account extension. There is a proxy server configured through a pac file. The extension isn't able to use the proxy to sign in to Azure. I hope this bug can be addressed so that I can use Cloud Shell from within VS Code.
Thanks!

**Comment by matt-chubb** [comment]
Followed all the steps online and still unable to get the extension to work behind a proxy configured from a pac file. Proxy environment variables added, configured proxy in settings.json and also disabled proxy strict ssl. Continue to get the same error. “You appear to be offline....”

**Comment by chrmarti** [comment]
Fixed in 0.8.1. Let me know if you still encounter any problems with this check.

**Comment by actislg** [comment]
I have the proxy environment variables configured. I'm seeing the same issue when I'm behind the corporate proxy. I have the latest version installed. 
![image](https://user-images.githubusercontent.com/795662/58056781-697da780-7b30-11e9-8c95-297cfd08042d.png)

**Comment by BradAF** [comment]
Hello, I am running into this error using a corporate proxy in version 0.8.4 on Windows 10. The proxy works fine for VS Code updates and browsing the Marketplace.

I have tried:
-  adding http_proxy, https_proxy user environmental variables
-  verifying proxy support set to: override 
- using Toggle Developer tools to watch for meaningful error messages with Verbose (not sure if I'm doing that right, though
![azureauth01](https://user-images.githubusercontent.com/11336928/61312665-e478dc80-a7c6-11e9-9b63-3ad7c6da308a.png)
)

I would be happy to provide any other information, please let me know!

**Comment by BradAF** [comment]
Hello, I am running into this error using a corporate proxy in version 0.8.4 on Windows 10. The proxy works fine for VS Code updates and browsing the Marketplace.

I have tried:
-  adding http_proxy, https_proxy user environmental variables
-  verifying proxy support set to: override 
- using Toggle Developer tools to watch for meaningful error messages with Verbose (not sure if I'm doing that right, though
![azureauth01](https://user-images.githubusercontent.com/11336928/61312665-e478dc80-a7c6-11e9-9b63-3ad7c6da308a.png)
)

I would be happy to provide any other information, please let me know!

**Comment by ColumCross** [comment]
I am having the same issue. I am behind a corporate proxy.

Azure Account Extension Version: 0.8.4

Azure App Service Extension Version: 0.15.0

VS Code Version:
Version: 1.37.1 (user setup)
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by chrmarti** [comment]
@ColumCross Could you retry with the Insiders version of VS Code, we recently fixed a bug in the loading of certificates on Windows which could be the issue you see: https://code.visualstudio.com/insiders/

If that doesn't work, please open a new issue as this is very likely a different problem than the one fixed here. Please include any errors shown in the console (Help > Toggle Developer Tools).

**Comment by ColumCross** [comment]
@chmarti Using the Insider Edition did not resolve my issue. I opened https://github.com/microsoft/vscode-azure-account/issues/147 as per your recommendation.
