### ISSUE TITLE
Cannot login with Vscode to Azure China Tenant

### ISSUE THREAD

**Issue by AlexWitecki** [microsoft/vscode-azure-account#222]
Hi,
When I login to Azure China tenant with VSCode I get error in browser:
AADSTS51004: The user account fqtF4t6xcEq9tOIBRK6OwQ== does not exist in the 7dabbfe5-826f-4410-979d-da6d8b1b2a89 directory. To sign into this application, the account must be added to the directory.

When I login normally to Azure China Portal it works. I have the newest Azure Account extension in Vscode. We noticed in the team that login with Vscode to China works in setup:
Azure Account : 0.8.11
VScode Version: 1.47.1 (user setup)

Please assist , the login error is affecting many members of my team.
Thank You
<img width="326" alt="error" src="https://user-images.githubusercontent.com/71078537/92729591-d85cc080-f372-11ea-9e6b-d92d0b4c384c.PNG">

**Comment by RMacfarlane** [comment]
@AlexWitecki I just published a new version of the extension, 0.9.3, that may fix this. Can you try using it?

**Comment by AlexWitecki** [comment]
Hi,
I just tested the content.
Sign in
Sorry, but we’re having trouble signing you in.
AADSTS51004: The user account fqtF4t6xcEq9tOIBRK6OwQ== does not exist in the 7dabbfe5-826f-4410-979d-da6d8b1b2a89 directory. To sign into this application, the account must be added to the directory.

But sorry, it is still not working for me :/

Regards,

Aleksander Witecki | Senior DevOps Engineer

EY GDS (CS) Poland sp. z o.o.
Office: 717143828 | aleksander.witecki@gds.ey.com<mailto:aleksander.witecki@gds.ey.com>
