### ISSUE TITLE
Fail to sign in with Azure account when setting the "Azure: Authentication Library" to "MSAL"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azure-account#316]
**OS:** Windows 10/ Linux
**VS Code Version:** 1.60.0
**Build:** 20210913.1
**Regression:** Not a regression

**Repro Steps:**
1. Install extensions: Azure Account and Azure Functions.
2. Set the "Azure: Authentication Library" setting to "MSAL".
3. Click the "Sign Out and Reload Window" button when popping up the below prompt.
![image](https://user-images.githubusercontent.com/57662131/133240528-b98f7ce1-1fc3-41b1-a958-8b4abb20df72.png)
4. F1 -> Click "Azure: Sign in".
5. Check whether succeed to sign in with Azure account.

**Expect:**
Succeed to sign in with Azure account.

**Actual:**
Fail to sign in with Azure account.
![image](https://user-images.githubusercontent.com/57662131/133238354-2a1de71d-0c4b-4f06-9076-f797861f143d.png)

**More Info:**
1. Verified on two Linux machines, this issue reproduces on these 2 machines.
2. Verified on four Windows machines, this issue reproduces on two of the machines.
3. Verified on one Mac machine, this issue does not reproduce.

**Comment by wwlorey** [comment]
Running "Azure: Sign In" for MSAL on my Windows VM I see the following error in the console:

> 'AADSTS53000: Device is not in required device state: compliant. Conditional Access policy requires a compliant device, and the device is not compliant. The user must enroll their device with an approved MDM provider like Intune.\r\nTrace ID: cefae570-13cb-41ea-a908-bb9a00d55101\r\nCorrelation ID: 7106d817-528f-4bf3-bb9c-69efe3e9dd87\r\nTimestamp: 2021-09-14 19:13:51Z'

Makes sense because my VM isn't registered with Intune and I'm attempting to sign in with my Microsoft account. 

The error isn't surfaced though because we swallow errors. That'll be fixed in https://github.com/microsoft/vscode-azure-account/issues/149.

> 1. Verified on two Linux machines, this issue reproduces on these 2 machines.
> 2. Verified on four Windows machines, this issue reproduces on two of the machines.

@v-xinda, is it the case that the Linux machines and the two Windows machines that you could repro on are *not* registered with Intune?

**Comment by wwlorey** [comment]
I was able to successfully sign in using an account that doesn't have the "compliant device" conditional access policy in place.

**Comment by v-xinda** [comment]
@wwlorey I can sign in successfully on Windows machine after signing in with Azure account in Edge. 
On Linux machine, I still fail to sign in azure account in VSCode when setting the "Azure: Authentication Library" to "MSAL".

**Comment by wwlorey** [comment]
When authenticating with a Microsoft account using MSAL, you must be on a managed device (i.e. the company portal/Intune needs to be installed). Unfortunately there isn't an Intune client for Linux so Linux machines cannot be managed. For this reason we won't be able to support MSAL on Linux ☹️

 I would link docs on this but the page is internal only.
