### ISSUE TITLE
Azure Cloud Shell fails to launch on macOS

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azure-account#959]
Creating a new issue because https://github.com/microsoft/vscode-azure-account/issues/719 is actually two separate issues, one for Linux, and one for macOS. I will leave #719 for the Linux bug.

- VS Code Version: 1.90.0-insider
- Azure Account Extension Version: 0.11.7 (and previous versions)
- OS Version: Apple M2 Pro - macOS Sonoma 14.4.1

Are you connected to a proxy server? No

Steps to Reproduce:

1. Launch Azure Cloud Shell bash or powershell on macOS

`
The terminal process "/Users/alex/dev/core/vscode-azureresourcegroups/bin/node.sh '/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)', '-e', 'require('/Users/alex/dev/core/vscode-azureresourcegroups/dist/cloudConsoleLauncher').main()', '--ms-enable-electron-run-as-node'" terminated with exit code: 9.
`

In the terminal for a brief second it displays the following error:
`/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin) -app/Contents/MacOS/Code - Insiders Helper (Plugin): bad option:
—-ms-enable-electron-run-as-node`

**Comment by arana2** [comment]
I'm also experiencing the same issue.

- VS Code Version: 1.89.0 (Universal)
- Azure Account Extension Version: 0.11.7 (and also tried 0.11.2)
- OS Version: Apple M3 Pro - macOS Sonoma 14.4.1

1. Launch Azure Cloud Shell bash or powershell on macOS
The terminal process "/Users/andrew/.vscode/extensions/ms-vscode.azure-account-0.11.7/bin/node.sh '/Users/andrew/Documents/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)', '-e', 'require('/Users/andrew/.vscode/extensions/ms-vscode.azure-account-0.11.7/dist/cloudConsoleLauncher').main()', '--ms-enable-electron-run-as-node'" failed to launch (exit code: 9).

I may have missed it, but I didn't see any errors outputted from the terminal.

**Comment by atom2-source** [comment]
Yeah doesn't work on my Mac either frustrating

**Comment by alexweininger** [comment]
This issue has been fixed in the latest version of the Azure Resources extension 🎉 which now contains the Cloud Shell feature. See the [v0.9.0 release notes](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.9.0) for more info.

**Comment by arana2** [comment]
Looks good on my end, @alexweininger!

**Azure Cloud Shell - Bash**
Thank you!
<img width="1441" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/38359810/db2d3814-af8e-47ba-a91b-7b0e46da7ccb">

**Azure Cloud Shell - Powershell**
<img width="1434" alt="image" src="https://github.com/microsoft/vscode-azure-account/assets/38359810/b597c88e-c2ff-4abd-ac35-3e85fe484cf9">

**Comment by atom2-source** [comment]
Thanks if its fixed I just plugged my pc in and used that instead of my mac.solved the issue quick on end.

**Comment by pablo-opss** [comment]
Launching cloudshell still fails on launching triggered by an extension. In my case azure terraform.
